import SuffixArrayGenerator
import RandomRNAStringGenerator

stringToBeProcessed = RandomRNAStringGenerator.generateString(100)
SuffixArrayGenerator.generateBWT(SuffixArrayGenerator.generateSuffixArray(stringToBeProcessed))