import SuffixArrayGenerator
import RandomRNAStringGenerator

stringToBeProcessed = "mmiissiissiippii"
    #RandomRNAStringGenerator.generateString(100)
SuffixArrayGenerator.generateBWT(SuffixArrayGenerator.generateSuffixArray(stringToBeProcessed))
SuffixArrayGenerator.genCTable(stringToBeProcessed)